version: '3'
services:  
  db:
    image: postgres:13.4
    volumes:
      - ./data-1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=gopher
      - POSTGRES_DB=gopher_corp

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=gopher
       - DB_PASSWORD=P@ssw0rd
       - DB_HOST=db
       - DB_NAME=gopher_corp 
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,dbuser
    ports:
      - "5432:5432"
    depends_on:
      - db